### ISSUE TITLE
winpilot@2024.5.19: hash check failed

### ISSUE THREAD

**Issue by clin1234** [Capella87/capella-bucket#2]
Checking hash of Winpilot.zip ... ERROR Hash check failed!
App:         Capella87_capella-bucket/winpilot
URL:         https://github.com/builtbybel/Winpilot/releases/download/2024.5.19/Winpilot.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    36525b0f66d523043cbab00384afaa7b9fdae21e7880617695299edbda9dca57
Actual:      265bb9ae60e17757b72fa147d4fedcba1ac217ff59f093fd7e8189e1698a0c77

**Comment by Capella87** [comment]
Thank you for precious issue reporting!
